version: '3.9'

name: linda

services:

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - my-app:/data/db 
    restart: always 

  nestjs:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.dev
    depends_on:
      - mongo
    restart: always 

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile.dev
    ports:
      - '5000:5000' 
    environment:
      NODE_ENV_MODE: "dev" 
    depends_on:
      - vite_react
    restart: always 

  vite_react:
    build:
      context: .
      dockerfile: website/Dockerfile.dev
    ports:
      - '4173:4173' 
    depends_on:
      - nestjs
    restart: always  

volumes:
  my-app: